# Generated by Django 3.2.9 on 2021-12-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_shopuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'М'), ('F', 'Ж'), ('U', 'Н')], max_length=3),
        ),
    ]
